# Generated by Django 4.2.7 on 2024-02-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identify_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(default='media/plant_images/plant.jpg', upload_to='plant_images/'),
            preserve_default=False,
        ),
    ]
