# Generated by Django 4.2.7 on 2024-04-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identify_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
    ]
