# Generated by Django 4.2.7 on 2024-03-20 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identify_app', '0004_achievement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='first_critical_rare',
            new_name='first_critical',
        ),
    ]
