# Generated by Django 4.2.7 on 2024-03-20 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identify_app', '0005_rename_first_critical_rare_achievement_first_critical'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='first_identification',
            new_name='first_near_threatened',
        ),
    ]
