# Generated by Django 4.2.7 on 2024-03-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identify_app', '0006_rename_first_identification_achievement_first_near_threatened'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='first_identification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievement',
            name='xp_at_1000_or_more',
            field=models.BooleanField(default=False),
        ),
    ]
